development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis #si on veut que Heroku marche on remplace redis par async
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %> #supprimer les deux lignes suivantes
  channel_prefix: LP4B_production
